export const ADD_TWITTER_ACCOUNT = "ADD_TWITTER_ACCOUNT";
export const ADD_REDDIT_ACCOUNT = "ADD_REDDIT_ACCOUNT";
export const UPDATE_ACCOUNTS = "UPDATE_ACCOUNTS";
export const REMOVE_ACCOUNTS = "REMOVE_ACCOUNTS";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const CLEAR_ACCOUNT = "CLEAR_ACCOUNT";
